
### C
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Model": "user",
    "Action": "Create",
    "Data": [
        {"Name": "test5", "Age": 55, "Address": "shanghai"},
        {"Name": "test6", "Age": 66, "Address": "shanghai"}
    ]
}

### R
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Action": "QueryFirst",
    "Model": "user",
    "Filter": {"Id": [1]},
    "Select": ["id", "name", "age", "Address"]
}

### R
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Action": "QueryMany",
    "Model": "user",
    "Select": ["id", "name", "age", "Address"],
    "Order": "id desc"
}

### R
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Action": "QueryPage",
    "Model": "user",
    "Select": ["id", "name", "age", "Address"],
    "Order": "id desc",
    "PageSize": 2
}

### U
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Model": "user",
    "Action": "Update",
    "Data": {"Age": "666666"},
    "Filter": {"Age": [666]}
}

### D
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Model": "user",
    "Method": "delete",
    "Filter": {"Age": [77]}
}

### C
POST http://localhost:8080/crud
Content-Type: application/json

{
    "Model": "user",
    "Method": "count",
    "Filter": {"Age": [22]}
}